"""API schemas"""

from .hardware import (
    MaterialBase,
    MaterialCreate,
    MaterialRead,
    ToleranceBase,
    ToleranceCreate,
    ToleranceRead,
    SurfaceFinishBase,
    SurfaceFinishCreate,
    SurfaceFinishRead,
    HardwarePartBase,
    HardwarePartCreate,
    HardwarePartRead,
    HardwarePartUpdate,
)
from .supplier import (
    SupplierCapabilityBase,
    SupplierCapabilityCreate,
    SupplierCapabilityRead,
    SupplierBase,
    SupplierCreate,
    SupplierRead,
    SupplierUpdate,
    SupplierQuoteBase,
    SupplierQuoteCreate,
    SupplierQuoteRead,
)
from .factory import (
    MachineBase,
    MachineCreate,
    MachineRead,
    MachineUpdate,
    ProductionJobBase,
    ProductionJobCreate,
    ProductionJobRead,
    ProductionJobUpdate,
    FactoryConfigBase,
    FactoryConfigCreate,
    FactoryConfigRead,
    FactoryConfigUpdate,
)
from .cad import (
    BoundingBox,
    CADModelBase,
    CADModelCreate,
    CADModelRead,
    CADAnalysisBase,
    CADAnalysisCreate,
    CADAnalysisRead,
    CADAnalysisUpdate,
)

__all__ = [
    # Hardware
    "MaterialBase",
    "MaterialCreate",
    "MaterialRead",
    "ToleranceBase",
    "ToleranceCreate",
    "ToleranceRead",
    "SurfaceFinishBase",
    "SurfaceFinishCreate",
    "SurfaceFinishRead",
    "HardwarePartBase",
    "HardwarePartCreate",
    "HardwarePartRead",
    "HardwarePartUpdate",
    # Supplier
    "SupplierCapabilityBase",
    "SupplierCapabilityCreate",
    "SupplierCapabilityRead",
    "SupplierBase",
    "SupplierCreate",
    "SupplierRead",
    "SupplierUpdate",
    "SupplierQuoteBase",
    "SupplierQuoteCreate",
    "SupplierQuoteRead",
    # Factory
    "MachineBase",
    "MachineCreate",
    "MachineRead",
    "MachineUpdate",
    "ProductionJobBase",
    "ProductionJobCreate",
    "ProductionJobRead",
    "ProductionJobUpdate",
    "FactoryConfigBase",
    "FactoryConfigCreate",
    "FactoryConfigRead",
    "FactoryConfigUpdate",
    # CAD
    "BoundingBox",
    "CADModelBase",
    "CADModelCreate",
    "CADModelRead",
    "CADAnalysisBase",
    "CADAnalysisCreate",
    "CADAnalysisRead",
    "CADAnalysisUpdate",
]
